### ISSUE TITLE
Feature: Add Holiday Spirit Graphics

### ISSUE THREAD

**Issue by TimmekHW** [LlmKira/novelai-python#86]
add pls "Add some holiday spirit."
![image](https://github.com/user-attachments/assets/b160cfec-be91-4727-a36c-c926eb8f3472)

**Comment by sudoskys** [comment]
This functionality is provided by the random prompt component. We will fix it later. You can add some holiday words manually to achieve the same effect.

**Comment by sudoskys** [comment]
link to #82
